modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="remeke"
version="1.0.0"
displayName="Remek"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="sitni, MCreator"

[[dependencies.remeke]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




