modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="grandcraft"
version="0.1"
displayName="GrandCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ExoFy, Rukolom"

[[dependencies.grandcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




